apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: clasificador-solicitudes-pba
  namespace: openshift-ai
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: pvc://mlflow-models/clasificador_solicitudes_pba_v1
      runtime: python
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
      env:
        - name: MODEL_INPUT_COLUMN
          value: "texto_solicitud"
